### ISSUE TITLE
leveldown.target.mk:recipe for target 'Release/obj.target/leveldown/src/batch.o' failed

### ISSUE THREAD

**Issue by binarykitchen** [Level/leveldown#148]
I am seeing a crash when installing leveldown on Ubuntu 14.10 with node.js v0.11.15

```
leveldown.target.mk:105: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/home/michael-heuberger/binarykitchen/code/twitter.videomail.io/node_modules/level/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-24-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael-heuberger/binarykitchen/code/twitter.videomail.io/node_modules/level/node_modules/leveldown
gyp ERR! node -v v0.11.15
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
```

**Comment by binarykitchen** [comment]
And maybe these lines from `npm-debug.log` are useful?

```
1847 verbose unlock done using /home/michael-heuberger/.npm/_locks/level-a75329fbec7e87c8.lock for /home/michael-heuberger/binarykitchen/code/twitter.videomail.io/node_modules/level
1848 verbose stack Error: leveldown@0.10.2 install: `node-gyp rebuild`
1848 verbose stack Exit status 1
1848 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
1848 verbose stack     at ChildProcess.emit (events.js:110:17)
1848 verbose stack     at maybeClose (child_process.js:1008:16)
1848 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
1849 verbose pkgid leveldown@0.10.2
1850 verbose cwd /home/michael-heuberger/binarykitchen/code/twitter.videomail.io
1851 error Linux 3.16.0-24-generic
1852 error argv "/usr/bin/node" "/usr/bin/npm" "i" "level"
1853 error node v0.11.15
1854 error npm  v2.1.6
1855 error code ELIFECYCLE
1856 error leveldown@0.10.2 install: `node-gyp rebuild`
1856 error Exit status 1
1857 error Failed at the leveldown@0.10.2 install script.
```

**Comment by binarykitchen** [comment]
maybe needs an update to latest nan?

**Comment by binarykitchen** [comment]
linked to https://github.com/ssbc/scuttlebot/issues/78

**Comment by rvagg** [comment]
```
leveldown.target.mk:105: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
```

is there anything before that line to say what's wrong with batch.o?

**Comment by mcollina** [comment]
@binarykitchen You should try: https://github.com/rvagg/node-leveldown/pull/146, it is 0.10.2 _but_ with the latest nan.

**Comment by binarykitchen** [comment]
@rvagg yes, lots of warnings and errors. Here a sample:

```
...
../src/leveldown.h:58:7: note: in expansion of macro ‘LD_RETURN_CALLBACK_OR_ERROR’
       LD_RETURN_CALLBACK_OR_ERROR(callback, #name " cannot be an empty String") \
       ^
../src/batch.cc:124:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/leveldown.h:83:7: error: ‘GetCurrent’ is not a member of ‘v8::Context’
       v8::Context::GetCurrent()->Global(), callback, argc, argv);
       ^
../src/leveldown.h:76:5: note: in expansion of macro ‘LD_RUN_CALLBACK’
     LD_RUN_CALLBACK(callback, 1, argv)                                         \
     ^
../src/leveldown.h:58:7: note: in expansion of macro ‘LD_RETURN_CALLBACK_OR_ERROR’
       LD_RETURN_CALLBACK_OR_ERROR(callback, #name " cannot be an empty String") \
       ^
../src/batch.cc:124:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
../src/batch.cc: In static member function ‘static void leveldown::Batch::Write(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/leveldown.h:83:7: error: ‘GetCurrent’ is not a member of ‘v8::Context’
       v8::Context::GetCurrent()->Global(), callback, argc, argv);
       ^
../src/batch.cc:171:5: note: in expansion of macro ‘LD_RUN_CALLBACK’
     LD_RUN_CALLBACK(v8::Local<v8::Function>::Cast(args[0]), 0, NULL);
     ^
In file included from ../src/batch.cc:5:0:
../node_modules/nan/nan.h: In instantiation of ‘void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
../node_modules/nan/nan.h:717:34:   required from here
../node_modules/nan/nan.h:373:5: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
     ^
../src/batch.cc: In static member function ‘static v8::Handle<v8::Value> leveldown::Batch::NewInstance(v8::Handle<v8::Object>, v8::Handle<v8::Object>)’:
../src/batch.cc:81:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
leveldown.target.mk:105: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
...
```

**Comment by rvagg** [comment]
Right, what @mcollina said then. I'll try and get my head around a release asap, kind of overloaded ATM though.

**Comment by binarykitchen** [comment]
thanks @rvagg - really appreciate it!

if you are stressed, how about merging matteo's PR into a beta version like 0.10.2-beta and publish that for now?

**Comment by binarykitchen** [comment]
@rvagg @mcollina ummm, sorry folks but is there an ETA when the next version is on npm?

**Comment by ralphtheninja** [comment]
@binarykitchen `leveldown@1.0.2` works for me on node `0.11.16`. Are you still seeing these issues?

**Comment by binarykitchen** [comment]
switched to iojs and works fine there

**Comment by ralphtheninja** [comment]
:+1:

**Comment by garthk** [comment]
Anyone coming here trying to `npm install` the Auth0 AD client, try Node 4 instead of Node 6.
