### ISSUE TITLE
install fails, gets 404 when trying to get non-existent node binaries

### ISSUE THREAD

**Issue by bjackson** [Level/leveldown#193]
When I try to install leveldown, this is the output I receive: 
```
$ npm install leveldown --save
|
> leveldown@1.0.2 install /Users/brett/code/friends/node_modules/leveldown
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.0/node-v2.3.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/brett/code/friends/node_modules/leveldown
gyp ERR! node -v v2.3.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "leveldown" "--save"
npm ERR! node v2.3.0
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

The file at http://nodejs.org/dist/v2.3.0/node-v2.3.0.tar.gz does not exist. 2.3.0 is the io.js version I am running, but it seems to be trying to get that version from the nodejs.org website, which predictably, doesn't have it.

**Comment by rvagg** [comment]
You have to use the node-gyp that comes with io.js, i.e. the one bundled with the npm bundled with io.js, you can't use a vanilla one so you can't upgrade npm and expect it to still work.

Lots of alternatives though:

1. download the io.js source tarball for your version and unpack it to ~/.node-gyp/ and node-gyp will skip this step
2. use https://github.com/mafintosh/node-gyp-install to install it (I think this works for this right @mafintosh?)
3. install pangyp and use `--node-gyp=pangyp` when you use `npm` and it'll use pangyp instead (I haven't actually tried this but I'm lead to believe it works)

**Comment by ralphtheninja** [comment]
2. Works perfectly

**Comment by bjackson** [comment]
Thanks all!

**Comment by rgbkrk** [comment]
Thank you for this issue and alternatives. I'm using 2.
