### ISSUE TITLE
Node.js v4.0.0 - Failed to require LevelDOWN

### ISSUE THREAD

**Issue by robogeek** [Level/leveldown#221]
I have a simple app, and testing compatibility with v4.0.0 ..

```
$ cat package.json 
{
  "name": "application-name",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node app"
  },
  "dependencies": {
    "express": "3.1.0",
    "ejs": "*",
    "async": "*",
    "sqlite3": "*",
    "sequelize": "*",
    "mongoose": "*",
    "levelup": "*",
    "leveldown": "*"
  }
}
```

I've done npm install, and that went through correctly.

Running the app gives this error message:

```
$ /usr/local/node-v4.0.0-linux-x64/bin/node app.js 

/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/levelup/lib/util.js:54
    throw requireError(e)
    ^
LevelUPError: Failed to require LevelDOWN (Module did not self-register.). Try `npm install leveldown` if it's missing
    at requireError (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/levelup/lib/util.js:60:10)
    at getLevelDOWN (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/levelup/lib/util.js:54:11)
    at LevelUP.open (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/levelup/lib/levelup.js:114:37)
    at new LevelUP (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/levelup/lib/levelup.js:87:8)
    at LevelUP (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/levelup/lib/levelup.js:47:12)
    at Object.exports.connect (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/models-levelup/notes.js:5:10)
    at Object.<anonymous> (/home/david/drobo/NodeWebDevelopment/book-rev2/filez/chap06/notes/app.js:42:7)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

**Comment by No9** [comment]
Hi @robogeek 

I tried to replicate this using your package.json
```
$ node -v
v4.0.0
$ node-gyp -v 
v3.0.1
```
And running the simple test app from levelup.
```
var levelup = require('levelup')

var db = levelup('./mydb')

// 2) put a key & value
db.put('name', 'LevelUP', function (err) {
  if (err) return console.log('Ooops!', err) // some kind of I/O error

  // 3) fetch by key
  db.get('name', function (err, value) {
    if (err) return console.log('Ooops!', err) // likely the key was not found

    // ta da!
    console.log('name=' + value)
  })
})
```
But I can't replicate the problem.
The `Module did not self-register.` hints at an ABI issue
Have you rebuilt leveldown the module since your upgrade to v4.0.0?
```
npm remove leveldown
npm install leveldown
```

**Comment by robogeek** [comment]
I did 

```
$ rm -rf node_modules
$ npm install
```

Effectively the same thing.  

The two systems I have available are:  a) MacBook Pro running OS X 10.10, b) Ubuntu 14.04

**Comment by No9** [comment]
@robogeek 
Can you confirm your setup please
Don't use the full path like you are doing when you actually run app.js
i.e. **NOT** /usr/local/node-v4.0.0-linux-x64/bin/node -v
```
$ node -v
v4.0.0
$ node-gyp -v 
v3.0.1
```

**Comment by robogeek** [comment]
Hmm... I set the PATH so like so:

```
$ export PATH=/usr/local/node-v4.0.0-linux-x64/bin:${PATH}
```

And then the node command line worked as you said, and then npm install did a full compile of the leveldb/etc sources, and now my app works correctly.
