### ISSUE TITLE
Issue when (re)installed as a bundled dependency

### ISSUE THREAD

**Issue by julien-f** [Level/leveldown#236]
leveldown binding are not found when a package using it as a bundled dependency is reinstalled.

When installed for the first time, it works normally:

```
> npm i ./foo
> ./node_modules/.bin/foo
it works!
```

When reinstalled, it failed:

```
it does not work :(
Error: Could not locate the bindings file. Tried:
 → /tmp/node_modules/foo/node_modules/leveldown/build/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/build/Debug/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/build/Release/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/out/Debug/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/Debug/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/out/Release/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/Release/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/build/default/leveldown.node
 → /tmp/node_modules/foo/node_modules/leveldown/compiled/4.2.2/linux/x64/leveldown.node
    at bindings (/tmp/node_modules/foo/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/tmp/node_modules/foo/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/node_modules/foo/index.js:4:3)
    at Module._compile (module.js:435:26)
```

See https://github.com/julien-f/issue-bundled-leveldown for an example.

**Comment by julien-f** [comment]
Tested with Node 4.2.2 and npm 3.3.12.

**Comment by ralphtheninja** [comment]
Lets continue here. Closing other issue if you don't mind.

**Comment by ralphtheninja** [comment]
Precond:

```bash
npm i npm@3.3.12 -g
```

Script to reproduce. Run in empty directory.

```bash
git clone https://github.com/julien-f/issue-bundled-leveldown
cd issue-bundled-leveldown
cd foo
npm i
cd ..
npm pack foo
mv foo-0.0.0.tgz ..
cd ..
mkdir node_modules

# this works
npm i foo-0.0.0.tgz --verbose # note the npm output
./node_modules/.bin/foo

# this fails
npm i foo-0.0.0.tgz --verbose # different output compared to first one
./node_modules/.bin/foo
```

Retry by wiping `node_modules`:

```bash
rm node_modules -rf && mkdir node_modules
npm i foo-0.0.0.tgz --verbose
./node_modules/.bin/foo
npm i foo-0.0.0.tgz --verbose
./node_modules/.bin/foo
```

**Comment by ralphtheninja** [comment]
@julien-f Closing this. Iirc we came to the conclusion that it was a npm problem, right? Re-open if not. Cheers.
