### ISSUE TITLE
Installation on Ubuntu Error 

### ISSUE THREAD

**Issue by ronyrun** [Level/leveldown#254]
Hello, 

Sorry I'm not an expert concerning the node installation....
I tried to launch  prebuild install and get this error,

would you please help me ?
node --version v5.6.0

When trying to install leveldown : 

```
> leveldown@1.4.4 install /srv/nodejs/myapp/node_modules/leveldown
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v5.6.0 are not available
make: Entering directory `/srv/nodejs/myapp/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
make: g++: Command not found
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o] Error 127
make: Leaving directory `/srv/nodejs/myapp/node_modules/leveldown/build'
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/srv/nodejs/myapp/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:100:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:185:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/srv/nodejs/myapp/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:100:13)
prebuild ERR! build     at ChildProcess.emit (events.js:185:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

with prebuild installed globaly I tried that : 
```
root@user:/srv/nodejs/myapp# prebuild --install
prebuild info begin Prebuild version 3.0.1
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/prebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/srv/nodejs/myapp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/prebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/5.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/5.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/prebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/srv/nodejs/myapp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /srv/nodejs/myapp) while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/prebuild/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:100:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:185:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/usr/local/lib/node_modules/prebuild/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:100:13)
prebuild ERR! build     at ChildProcess.emit (events.js:185:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

**Comment by ralphtheninja** [comment]
Hmm for some reason prebuild can't find any prebuilts for you, but there should be prebuilt for Ubuntu. I'd really like to nail this one. Can you try doing

`npm install leveldown --verbose`

And put that output in a gist and share the link here?

**Comment by ralphtheninja** [comment]
It would also be useful to know the values of `process.arch`, `process.platform` and `process.versions`, just type `node` to open the repl. For me this gives:

```
$ node
> process.arch
'x64'
> process.platform
'linux'
> process.versions
{ http_parser: '2.6.1',
  node: '5.6.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2f' }
```

**Comment by ralphtheninja** [comment]
@ronyrun Are you behind a proxy?

**Comment by alexcheninfo** [comment]
I'm not able to install Leveldown either (Ubuntu 15.10 on a 64 bit AMD machine):

```
alex@alex-M52AD-M12AD-A-F-K31AD:~/node/project$ npm install leveldown --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/alex/.nvm/versions/node/v5.0.0/bin/node',
npm verb cli   '/home/alex/.nvm/versions/node/v5.0.0/bin/npm',
npm verb cli   'install',
npm verb cli   'leveldown',
npm verb cli   '--verbose' ]
npm info using npm@3.3.6
npm info using node@v5.0.0
npm verb request uri https://registry.npmjs.org/leveldown
npm verb request no auth needed
npm info attempt registry request try #1 at 10:51:33 PM
npm verb request id 4c9833a26140e0af
npm http request GET https://registry.npmjs.org/leveldown
npm http 200 https://registry.npmjs.org/leveldown
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers   etag: '"7YSZTQCNRZ0IO3O2GD2JW7X88"',
npm verb headers   'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '157978',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Sat, 13 Feb 2016 14:51:33 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '115',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hkg6826-HKG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1455375093.542477,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb get saving leveldown to /home/alex/.npm/registry.npmjs.org/leveldown/.cache.json
npm verb cache add spec leveldown
npm verb addNamed "*" is a valid semver range for leveldown
npm verb addNameRange registry:https://registry.npmjs.org/leveldown not in flight; fetching
npm verb get https://registry.npmjs.org/leveldown not expired, no request
npm verb addNamed "1.4.4" is a plain semver version for leveldown
npm verb addRemoteTarball https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz',
npm verb addRemoteTarball   '5978b7b3e7ffa595b179391126035a9717ead765' ]
npm info retry fetch attempt 1 at 10:51:34 PM
npm info attempt registry request try #1 at 10:51:34 PM
npm http fetch GET https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz
npm http fetch 200 https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz
npm verb addTmpTarball /tmp/npm-8925-4472df33/registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for leveldown@1.4.4
npm verb afterAdd /home/alex/.npm/leveldown/1.4.4/package/package.json not in flight; writing
npm verb afterAdd /home/alex/.npm/leveldown/1.4.4/package/package.json written
npm verb request uri https://registry.npmjs.org/abstract-leveldown
npm verb request no auth needed
npm info attempt registry request try #1 at 10:51:36 PM
npm http request GET https://registry.npmjs.org/abstract-leveldown
npm http 200 https://registry.npmjs.org/abstract-leveldown
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers   etag: '"49J8A8D38LQICSTNFEZX4KGQK"',
npm verb headers   'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '115916',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Sat, 13 Feb 2016 14:51:37 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hkg6826-HKG',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1455375096.332348,VS0,VE1491',
npm verb headers   vary: 'Accept' }
npm verb get saving abstract-leveldown to /home/alex/.npm/registry.npmjs.org/abstract-leveldown/.cache.json
npm verb cache add spec abstract-leveldown@~2.4.0
npm verb addNamed ">=2.4.0 <2.5.0" is a valid semver range for abstract-leveldown
npm verb addNameRange registry:https://registry.npmjs.org/abstract-leveldown not in flight; fetching
npm verb get https://registry.npmjs.org/abstract-leveldown not expired, no request
npm verb addNamed "2.4.1" is a plain semver version for abstract-leveldown
npm verb addRemoteTarball https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz',
npm verb addRemoteTarball   'b3bfedb884eb693a12775f0c55e9f0a420ccee64' ]
npm info retry fetch attempt 1 at 10:51:38 PM
npm info attempt registry request try #1 at 10:51:38 PM
npm http fetch GET https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz
npm http fetch 200 https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz
npm verb addTmpTarball /tmp/npm-8925-4472df33/registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-2.4.1.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for abstract-leveldown@2.4.1
npm verb afterAdd /home/alex/.npm/abstract-leveldown/2.4.1/package/package.json not in flight; writing
npm verb afterAdd /home/alex/.npm/abstract-leveldown/2.4.1/package/package.json written
npm verb request uri https://registry.npmjs.org/fsevents
npm verb request no auth needed
npm info attempt registry request try #1 at 10:51:39 PM
npm verb etag "D9PC4PL08KP2KF4WZ96D0QN5T"
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm verb headers { date: 'Sat, 13 Feb 2016 14:51:39 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"D9PC4PL08KP2KF4WZ96D0QN5T"',
npm verb headers   age: '107',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-hkg6824-HKG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '5',
npm verb headers   'x-timer': 'S1455375099.244342,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag https://registry.npmjs.org/fsevents from cache
npm verb get saving fsevents to /home/alex/.npm/registry.npmjs.org/fsevents/.cache.json
npm WARN install Couldn't install optional dependency: Unsupported
npm verb install Error: Unsupported
npm verb install     at checkPlatform (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:46:14)
npm verb install     at Array.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb install     at LOOP (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb install     at /home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm verb install     at checkEngine (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:25:10)
npm verb install     at Array.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb install     at LOOP (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb install     at chain (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm verb install     at module.exports.isInstallable (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/validate-args.js:26:3)
npm verb install     at resolveWithNewModule (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/deps.js:408:12)
npm verb lock using /home/alex/.npm/_locks/staging-67c35ae24f3c6fda.lock for /home/alex/node/project/node_modules/.staging
npm verb unbuild node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm verb gentlyRm don't care about contents; nuking /home/alex/node/project/node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm verb tar unpack /home/alex/.npm/leveldown/1.4.4/package.tgz
npm verb tar unpacking to /home/alex/node/project/node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm verb gentlyRm don't care about contents; nuking /home/alex/node/project/node_modules/.staging/leveldown-ca7bc831b0c29a053aa2192192bd2681
npm info lifecycle leveldown@1.4.4~preinstall: leveldown@1.4.4
npm info linkStuff leveldown@1.4.4
npm verb linkBins leveldown@1.4.4
npm verb linkMans leveldown@1.4.4
npm verb rebuildBundles leveldown@1.4.4
npm verb rebuildBundles [ 'abstract-leveldown' ]
npm info lifecycle leveldown@1.4.4~install: leveldown@1.4.4

> leveldown@1.4.4 install /home/alex/node/project/node_modules/leveldown
> prebuild --install

module.js:339
    throw err;
    ^

Error: Cannot find module './lib/utils'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/alex/node/project/node_modules/.bin/rc:2:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
npm verb lifecycle leveldown@1.4.4~install: unsafe-perm in lifecycle true
npm verb lifecycle leveldown@1.4.4~install: PATH: /home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/alex/node/project/node_modules/leveldown/node_modules/.bin:/home/alex/node/project/node_modules/.bin:/home/alex/mongodb/bin:/home/alex/.nvm/versions/node/v5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alex/.fzf/bin
npm verb lifecycle leveldown@1.4.4~install: CWD: /home/alex/node/project/node_modules/leveldown
npm info lifecycle leveldown@1.4.4~install: Failed to exec install script
npm verb unlock done using /home/alex/.npm/_locks/staging-67c35ae24f3c6fda.lock for /home/alex/node/project/node_modules/.staging
npm verb stack Error: leveldown@1.4.4 install: `prebuild --install`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/home/alex/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid leveldown@1.4.4
npm verb cwd /home/alex/node/project
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/alex/.nvm/versions/node/v5.0.0/bin/node" "/home/alex/.nvm/versions/node/v5.0.0/bin/npm" "install" "leveldown" "--verbose"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.4 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.4.4 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/node/project/npm-debug.log
```

**Comment by ralphtheninja** [comment]
@alexcheninfo Would you mind opening up a separate issue for this? I don't think this is related to this issue.

**Comment by alexcheninfo** [comment]
@ralphtheninja Okay, I opened a new issue.

**Comment by ronyrun** [comment]
Hello, Sorry for the late answer.
Let me provide everything !
I'm not Behind a proxy.

```node
> process.arch
'arm'
> process.platform
'linux'
> process.versions
{ http_parser: '2.6.1',
  node: '5.6.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2f' }

```

Here is the end of the putty output (I'm figuring out how to get the whole stuff I'm on it) 

https://gist.github.com/ronyrun/1c11af5459741a83f631

**Comment by ralphtheninja** [comment]
Ok. That makes total sense in fact :) I'll make sure to get some prebuilts done for arm. In the meantime you can do

`sudo apt-get install build-essential`

so you can compile the binaries. You need this anyway for all other native modules on npm.

**Comment by ralphtheninja** [comment]
@ronyrun Out of curiosity. What kind of machine/device are you running on?

**Comment by ronyrun** [comment]
@ralphtheninja I'm on a VM on Scaleway

https://www.scaleway.com/pricing/

4 Dedicated ARM Cores
2GB Memory
50GB SSD Disk
1 Reserved public IPv4

**Comment by ronyrun** [comment]
Thanks I'll give a try with this command !

**Comment by ralphtheninja** [comment]
Arm binaries uploaded

![screenshot from 2016-02-14 18 46 29](https://cloud.githubusercontent.com/assets/308049/13035253/33b5569c-d34b-11e5-9902-8ca286432986.png)

@ronyrun Let me know how things goes

**Comment by ronyrun** [comment]
Ok

**Comment by ralphtheninja** [comment]
@ronyrun Any progress? If it works fine, just close this issue.

**Comment by ronyrun** [comment]
Hello,

the installation is successful with a `npm install leveldown` on my environment !
Thank you very much.
