### ISSUE TITLE
Can not run in window7 64 bit platform use electron 

### ISSUE THREAD

**Issue by milu2003** [Level/leveldown#316]
```
`
electron-packager . dxcspider --platform win32 --arch all  --out ./dist222 --overwrite  --asar --ignore='(dist222|.git)'
`
```

With this command in the Mac platform after the window 7 platform to open
And then there's the mistake

![image](https://cloud.githubusercontent.com/assets/15957433/19562587/7cbbae3a-970f-11e6-9d3f-4b705524fd44.png)

use in 
electron  v1.4.4
node  v6.9.1

and can run on Mac platform

**Comment by juliangruber** [comment]
cc @0x00A

**Comment by 0x00A** [comment]
Relevant links...
https://github.com/electron-userland/electron-packager/issues/512
https://github.com/nodejs/node-gyp/issues/1040

**Comment by milu2003** [comment]
I compile the project in the window, the previous error does not appear

But there has been a new error, I tried a night, or can not be resolved.


![image](https://cloud.githubusercontent.com/assets/15957433/19629970/9f78dc7c-99b2-11e6-9cc5-a89843af8840.png)



```
`
K:\>cd node_modules

K:\node_modules>cd leveldown

K:\node_modules\leveldown>node-gyp rebuild --target=1.4.4 --arch=x64 --dist-url=
https://atom.io/download/atom-shell
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Administrator.WIN-20160409UYF\\AppData\\Roamin
g\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'K:\\node_modules\\leveldown\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator.WIN-20160409UYF\\AppData\\Roamin
g\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator.WIN-20160409UYF\\.node-gyp\\iojs
-1.4.4\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator.WIN-20160409UYF\
\.node-gyp\\iojs-1.4.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator.WIN-20160409UYF\\
AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=K:\\node_modules\\leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'K:\\node_modules\\leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  leveldb.vcxproj -> K:\node_modules\leveldown\build\Release\\leveldb.lib
  snappy.vcxproj -> K:\node_modules\leveldown\build\Release\\snappy.lib
  batch.cc
  batch_async.cc
  database.cc
  database_async.cc
  iterator.cc
  iterator_async.cc
  leveldown.cc
  leveldown_async.cc
  win_delay_load_hook.cc
C:\Users\Administrator.WIN-20160409UYF\.node-gyp\iojs-1.4.4\Release\iojs.lib :
fatal error LNK1106: invalid file or disk full: cannot seek to 0xF2ADE [K:\node
_modules\leveldown\build\leveldown.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator.WIN-20160409UY
F\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator
.WIN-20160409UYF\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.j
s" "rebuild" "--target=1.4.4" "--arch=x64" "--dist-url=https://atom.io/download/
atom-shell"
gyp ERR! cwd K:\node_modules\leveldown
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

K:\node_modules\leveldown>

`
```



Who ever encountered this problem?

**Comment by milu2003** [comment]
I tried to lower the version, 
1.1.0 version replaced


The previous error is gone, the error occurred


![image](https://cloud.githubusercontent.com/assets/15957433/19630180/83e2fc04-99b7-11e6-880e-7de93c48e041.png)


![image](https://cloud.githubusercontent.com/assets/15957433/19630200/aa5d47fe-99b7-11e6-9cb2-ad6c2973ff6c.png)


```
`
C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider>cd node_modules

C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules>cd leveldow


C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules\leveldown>n
de-gyp rebuild --target=1.1.0 --arch=x64 --dist-url=https://atom.io/download/at
m-shell
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | win32 | x64
gyp http GET https://atom.io/download/atom-shell/v1.1.0/iojs-v1.1.0.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v1.1.0/iojs-v1.1.0.tar.gz
gyp http GET https://atom.io/download/atom-shell/v1.1.0/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v1.1.0/win-x86/iojs.lib
gyp http GET https://atom.io/download/atom-shell/v1.1.0/win-x64/iojs.lib
gyp http 200 https://atom.io/download/atom-shell/v1.1.0/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v1.1.0/win-x86/iojs.lib
gyp http 200 https://atom.io/download/atom-shell/v1.1.0/win-x64/iojs.lib
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Administrator.WIN-20160409UYF\\AppData\\Roami
g\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator.WIN-20160409UYF\\Desktop\\ESpid
r\\node_modules\\leveldown\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator.WIN-20160409UYF\\AppData\\Roami
g\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator.WIN-20160409UYF\\.node-gyp\\ioj
-1.1.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator.WIN-20160409UYF
\.node-gyp\\iojs-1.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator.WIN-20160409UYF\
AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Administrator.WIN-20160409U
F\\Desktop\\ESpider\\node_modules\\leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Administrator.WIN-20160409UYF\\Desktop\\ESpid
r\\node_modules\\leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  builder.cc
  db_impl.cc
  db_iter.cc
  filename.cc
  dbformat.cc
  log_reader.cc
  log_writer.cc
  memtable.cc
  repair.cc
  table_cache.cc
  version_edit.cc
C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules\leveldown\d
eps\leveldb\leveldb-1.19\db/skiplist.h(360): warning C4312: 'reinterpret_cast':
 conversion from 'int' to 'void *' of greater size (compiling source file level
db-1.19\db\memtable.cc) [C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider
\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
  C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules\leveldown
  \deps\leveldb\leveldb-1.19\db/skiplist.h(337): note: while compiling class te
  mplate member function 'void leveldb::SkipList<const char *,leveldb::MemTable
  ::KeyComparator>::Insert(const Key &)'
          with
          [
              Key=const char *
          ] (compiling source file leveldb-1.19\db\memtable.cc)
  leveldb-1.19\db\memtable.cc(105): note: see reference to function template in
  stantiation 'void leveldb::SkipList<const char *,leveldb::MemTable::KeyCompar
  ator>::Insert(const Key &)' being compiled
          with
          [
              Key=const char *
          ]
  C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules\leveldown
  \deps\leveldb\leveldb-1.19\db/memtable.h(79): note: see reference to class te
  mplate instantiation 'leveldb::SkipList<const char *,leveldb::MemTable::KeyCo
  mparator>' being compiled (compiling source file leveldb-1.19\db\memtable.cc)
  version_set.cc
  write_batch.cc
  memenv.cc
  block.cc
  block_builder.cc
  filter_block.cc
  format.cc
  iterator.cc
  merger.cc
  table.cc
  table_builder.cc
  two_level_iterator.cc
  arena.cc
  bloom.cc
  cache.cc
  coding.cc
  comparator.cc
  crc32c.cc
  env.cc
  filter_policy.cc
  hash.cc
  logging.cc
  options.cc
  status.cc
  port_uv.cc
  env_win.cc
  win_logger.cc
  win_delay_load_hook.cc
  leveldb.vcxproj -> C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\nod
  e_modules\leveldown\build\Release\\leveldb.lib
  snappy-sinksource.cc
  snappy-stubs-internal.cc
  snappy.cc
  win_delay_load_hook.cc
c:\users\administrator.win-20160409uyf\desktop\espider\node_modules\leveldown\d
eps\snappy\snappy-1.1.1\snappy-stubs-internal.h : warning C4819: The file conta
ins a character that cannot be represented in the current code page (936). Save
 the file in Unicode format to prevent data loss (compiling source file snappy-
1.1.1\snappy-stubs-internal.cc) [C:\Users\Administrator.WIN-20160409UYF\Desktop
\ESpider\node_modules\leveldown\deps\snappy\snappy.vcxproj]
c:\users\administrator.win-20160409uyf\desktop\espider\node_modules\leveldown\d
eps\snappy\snappy-1.1.1\snappy-stubs-internal.h : warning C4819: The file conta
ins a character that cannot be represented in the current code page (936). Save
 the file in Unicode format to prevent data loss (compiling source file snappy-
1.1.1\snappy.cc) [C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_m
odules\leveldown\deps\snappy\snappy.vcxproj]
  snappy.vcxproj -> C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node
  _modules\leveldown\build\Release\\snappy.lib
  batch.cc
  batch_async.cc
  database.cc
  database_async.cc
  iterator.cc
  iterator_async.cc
  leveldown.cc
  leveldown_async.cc
  win_delay_load_hook.cc
     Creating library C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\no
  de_modules\leveldown\build\Release\leveldown.lib and object C:\Users\Administ
  rator.WIN-20160409UYF\Desktop\ESpider\node_modules\leveldown\build\Release\le
  veldown.exp
  Generating code
  Finished generating code
  leveldown.vcxproj -> C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\n
  ode_modules\leveldown\build\Release\\leveldown.node
  leveldown.vcxproj -> C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\n
  ode_modules\leveldown\build\Release\leveldown.pdb (Full PDB)
gyp info ok

C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules\leveldown>c
 ..

C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider\node_modules>cd ..

C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider>npm start

> dxcspider@1.2.0 start C:\Users\Administrator.WIN-20160409UYF\Desktop\ESpider
> electron main.js
`
```

**Comment by milu2003** [comment]
```


The problem is solved, my negligence！！！

add this in package.json， I accidentally deleted before

```
 "devDependencies": {
      "electron-prebuilt": "1.2.1"
  },

```

![image](https://cloud.githubusercontent.com/assets/15957433/19642551/6ce142f2-9a18-11e6-96d7-ffa3a2ec519f.png)



So the solution to this problem is in the window below compile on the line.

Thank you for your help，@0x00A @juliangruber
