### ISSUE TITLE
Windows help

### ISSUE THREAD

**Issue by 0x00A** [Level/leveldown#317]
I'm trying to rebuild leveldown for use with electron on Windows (its the very latest Virtualbox, ie10 preview which is pre-configured by Microsoft). But I'm getting this ECONNRESET message from `prebuild`. Since i don't want to prebuild anyway, I cloned leveldown and then did `node-gyp rebuild`, but from that i also get `read ECONNRESET` in the error's stack. Are there any Windows Wizards that might have any idea what I'm doing wrong?

![image](https://cloud.githubusercontent.com/assets/136109/19566014/29710250-96e9-11e6-938c-a2f7d5692126.png)

**Comment by vweevers** [comment]
Can you share the output of `node-gyp rebuild --verbose`?

**Comment by 0x00A** [comment]
```
IEUser@MSEDGEWIN10 MINGW64 /c/work/voltra/node_modules/leveldown (master)
$ node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\IEUser\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.12\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.9.1
gyp verb command install [ '6.9.1' ]
gyp verb install input version string "6.9.1"
gyp verb install installing version: 6.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 6.9.1
gyp verb ensuring nodedir is created C:\Users\IEUser\.node-gyp\6.9.1
gyp verb created nodedir C:\Users\IEUser\.node-gyp\6.9.1
gyp http GET https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp verb extracted file from tarball include\node\android-ifaddrs.h
gyp verb extracted file from tarball include\node\ares.h
gyp verb extracted file from tarball include\node\ares_build.h
gyp verb extracted file from tarball include\node\ares_rules.h
gyp verb extracted file from tarball include\node\ares_version.h
gyp verb extracted file from tarball include\node\common.gypi
gyp verb extracted file from tarball include\node\config.gypi
gyp verb extracted file from tarball include\node\nameser.h
gyp verb extracted file from tarball include\node\node.h
gyp verb extracted file from tarball include\node\node_buffer.h
gyp verb extracted file from tarball include\node\node_object_wrap.h
gyp verb extracted file from tarball include\node\node_version.h
gyp verb extracted file from tarball include\node\pthread-barrier.h
gyp verb extracted file from tarball include\node\pthread-fixes.h
gyp verb extracted file from tarball include\node\stdint-msvc2008.h
gyp verb extracted file from tarball include\node\tree.h
gyp verb extracted file from tarball include\node\uv-aix.h
gyp verb extracted file from tarball include\node\uv-bsd.h
gyp verb extracted file from tarball include\node\uv-darwin.h
gyp verb extracted file from tarball include\node\uv-errno.h
gyp verb extracted file from tarball include\node\uv-linux.h
gyp verb extracted file from tarball include\node\uv-sunos.h
gyp verb extracted file from tarball include\node\uv-threadpool.h
gyp verb extracted file from tarball include\node\uv-unix.h
gyp verb extracted file from tarball include\node\uv-version.h
gyp verb extracted file from tarball include\node\uv-win.h
gyp verb extracted file from tarball include\node\uv.h
gyp WARN install got an error, rolling back install
gyp verb command remove [ '6.9.1' ]
gyp verb remove using node-gyp dir: C:\Users\IEUser\.node-gyp
gyp verb remove removing target version: 6.9.1
gyp verb remove removing development files for version: 6.9.1
gyp verb extracted file from tarball include\node\v8-debug.h
gyp verb extracted file from tarball include\node\v8-experimental.h
gyp verb extracted file from tarball include\node\v8-platform.h
gyp verb extracted file from tarball include\node\v8-profiler.h
gyp verb extracted file from tarball include\node\v8-testing.h
gyp verb extracted file from tarball include\node\v8-util.h
gyp verb extracted file from tarball include\node\v8-version.h
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
gyp ERR! cwd C:\work\voltra\node_modules\leveldown
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by vweevers** [comment]
The headers could be corrupt, because [that tarball](https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz) should contain a bunch more files after `v8-version.h`. I ran the same command on an almost identical setup, and this is the biggest difference I noticed in the log.

Try `node-gyp install 6.9.1` to redownload the headers.

**Comment by 0x00A** [comment]
I get this from running `node-gyp install 6.9.1 --verbose`...
```
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '6.9.1',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | win32 | x64
gyp verb command install [ '6.9.1' ]
gyp verb install input version string "6.9.1"
gyp verb install installing version: 6.9.1
gyp verb ensuring nodedir is created C:\Users\IEUser\.node-gyp\6.9.1
gyp verb created nodedir C:\Users\IEUser\.node-gyp\6.9.1
gyp http GET https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp verb extracted file from tarball include\node\android-ifaddrs.h
gyp verb extracted file from tarball include\node\ares.h
gyp verb extracted file from tarball include\node\ares_build.h
gyp verb extracted file from tarball include\node\ares_rules.h
gyp verb extracted file from tarball include\node\ares_version.h
gyp verb extracted file from tarball include\node\common.gypi
gyp verb extracted file from tarball include\node\config.gypi
gyp verb extracted file from tarball include\node\nameser.h
gyp verb extracted file from tarball include\node\node.h
gyp verb extracted file from tarball include\node\node_buffer.h
gyp verb extracted file from tarball include\node\node_object_wrap.h
gyp verb extracted file from tarball include\node\node_version.h
gyp verb extracted file from tarball include\node\pthread-barrier.h
gyp verb extracted file from tarball include\node\pthread-fixes.h
gyp verb extracted file from tarball include\node\stdint-msvc2008.h
gyp verb extracted file from tarball include\node\tree.h
gyp verb extracted file from tarball include\node\uv-aix.h
gyp verb extracted file from tarball include\node\uv-bsd.h
gyp verb extracted file from tarball include\node\uv-darwin.h
gyp verb extracted file from tarball include\node\uv-errno.h
gyp verb extracted file from tarball include\node\uv-linux.h
gyp verb extracted file from tarball include\node\uv-sunos.h
gyp verb extracted file from tarball include\node\uv-threadpool.h
gyp verb extracted file from tarball include\node\uv-unix.h
gyp verb extracted file from tarball include\node\uv-version.h
gyp verb extracted file from tarball include\node\uv-win.h
gyp verb extracted file from tarball include\node\uv.h
gyp WARN install got an error, rolling back install
gyp verb command remove [ '6.9.1' ]
gyp verb remove using node-gyp dir: C:\Users\IEUser\.node-gyp
gyp verb remove removing target version: 6.9.1
gyp verb remove removing development files for version: 6.9.1
gyp verb extracted file from tarball include\node\v8-debug.h
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "6.9.1" "--verbose"
gyp ERR! cwd C:\work\voltra\node_modules\leveldown
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by vweevers** [comment]
Given that I can't replicate, with the same node, node-gyp and VM, the issue must be with the network (either vbox or the host). Not sure where to go from here. If Wireshark could help, or if me sending you a vbox appliance or a Vagrantfile (so we can be sure the node stack is not the issue) is worth the trouble.

**Comment by 0x00A** [comment]
ok, no worries. I'll close this and continue to tinker :) thanks for the help though!

**Comment by vweevers** [comment]
ok, good luck!
