### ISSUE TITLE
Elastic Beanstalk woes

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/leveldown#326]
Having trouble installing on Amazon AWS Elastic Beanstalk service. Anyone know how to make it work? Other tips that might be useful?

```
-------------------------------------
/var/log/eb-activity.log
-------------------------------------
  npm ERR! npm  v3.10.8
  npm ERR! code ELIFECYCLE
  npm ERR! leveldown@1.5.0 install: `prebuild --install`
  npm ERR! Exit status 2
  npm ERR! 
  npm ERR! Failed at the leveldown@1.5.0 install script 'prebuild --install'.
  npm ERR! Make sure you have the latest version of node.js and npm installed.
  npm ERR! If you do, this is most likely a problem with the leveldown package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     prebuild --install
  npm ERR! You can get information on how to open an issue for this project with:
  npm ERR!     npm bugs leveldown
  npm ERR! Or if that isn't available, you can get their info via:
  npm ERR!     npm owner ls leveldown
  npm ERR! There is likely additional logging output above.
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /tmp/deployment/application/npm-debug.log
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1 (ElasticBeanstalk::ExternalInvocationError)
caused by: + /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install
  
  > dtrace-provider@0.6.0 install /tmp/deployment/application/node_modules/restify/node_modules/dtrace-provider
  > node scripts/install.js
  
  
  > leveldown@1.5.0 install /tmp/deployment/application/node_modules/leveldown
  > prebuild --install
  
  prebuild WARN install EACCES: permission denied, access '/tmp/.npm'
  prebuild ERR! clean error 
  prebuild ERR! stack Error: EACCES: permission denied, rmdir 'build'
  prebuild ERR! stack     at Error (native)
  prebuild ERR! not ok 
  prebuild ERR! build Error: EACCES: permission denied, rmdir 'build'
  prebuild ERR! build     at Error (native)
  
  npm ERR! Linux 4.4.30-32.54.amzn1.x86_64
  npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "--production" "rebuild"
  npm ERR! node v6.9.1
  npm ERR! npm  v3.10.8
  npm ERR! code ELIFECYCLE
  npm ERR! leveldown@1.5.0 install: `prebuild --install`
  npm ERR! Exit status 2
  npm ERR! 
  npm ERR! Failed at the leveldown@1.5.0 install script 'prebuild --install'.
  npm ERR! Make sure you have the latest version of node.js and npm installed.
  npm ERR! If you do, this is most likely a problem with the leveldown package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     prebuild --install
  npm ERR! You can get information on how to open an issue for this project with:
  npm ERR!     npm bugs leveldown
  npm ERR! Or if that isn't available, you can get their info via:
  npm ERR!     npm owner ls leveldown
  npm ERR! There is likely additional logging output above.
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /tmp/deployment/application/npm-debug.log
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)


[2016-12-13T14:50:53.204Z] INFO  [1961]  - [Application deployment app-fb3d-161213_154718@1/StartupStage0/AppDeployPreHook/50npm.sh] : Activity failed.
[2016-12-13T14:50:53.204Z] INFO  [1961]  - [Application deployment app-fb3d-161213_154718@1/StartupStage0/AppDeployPreHook] : Activity failed.
[2016-12-13T14:50:53.204Z] INFO  [1961]  - [Application deployment app-fb3d-161213_154718@1/StartupStage0] : Activity failed.
[2016-12-13T14:50:53.205Z] INFO  [1961]  - [Application deployment app-fb3d-161213_154718@1] : Completed activity. Result:
  Application deployment - Command CMD-Startup failed
[2016-12-13T15:00:20.580Z] INFO  [2282]  - [CMD-TailLogs] : Starting activity...
[2016-12-13T15:00:20.581Z] INFO  [2282]  - [CMD-TailLogs/AddonsBefore] : Starting activity...
[2016-12-13T15:00:20.581Z] INFO  [2282]  - [CMD-TailLogs/AddonsBefore] : Completed activity.
[2016-12-13T15:00:20.581Z] INFO  [2282]  - [CMD-TailLogs/TailLogs] : Starting activity...
[2016-12-13T15:00:20.581Z] INFO  [2282]  - [CMD-TailLogs/TailLogs/TailLogs] : Starting activity...
```

**Comment by juliangruber** [comment]
this looks like file system issues, with prebuild. would you mind reopening the issue on https://github.com/mafintosh/prebuild?

**Comment by fergiemcdowall** [comment]
Am happy to do that- but cant see which issue should be reopened. Which one is it?

**Comment by fergiemcdowall** [comment]
Oh- sorry- you mean to reopen THIS issue on prebuild. Doh! Yes, I can do that

**Comment by juliangruber** [comment]
thanks!
