### ISSUE TITLE
1.5.1 fails to npm install

### ISSUE THREAD

**Issue by bbondy** [Level/leveldown#331]
The recent release broke npm install for my project, I'm going to revert to the last known good version pinned, but just an FYI.

**Comment by juliangruber** [comment]
it works for me, can you give us more information about your setup and paste the error message?

**Comment by bbondy** [comment]
Sorry I don't have it up anymore but it was Node v7.3 on Windows x64 install.
Reverted to 1.5.0 worked.  npm install on 1.5.1 failed twice in a row.

**Comment by ralphtheninja** [comment]
cc @vweevers

**Comment by vweevers** [comment]
Tried leveldown 1.5.1 with node 7.3.0 and npm 3.10.10 on Windows 8.1 x64. No problems here.

> Sorry I don't have it up anymore

@bbondy can you go back and try again?

**Comment by chrisslater** [comment]
I am getting an issue with leveldown on windows too: v1.5.0 on node v7.3.0. 

For me it seems to be during prebuild with this error:
```
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp.
```

Full stack:

```
error C:\Users\Chris\Sites\blog\node_modules\level\node_modules\leveldown: Command failed.
Exit code: 2
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c prebuild --install
Directory: C:\Users\Chris\Sites\blog\node_modules\level\node_modules\leveldown
Output:
prebuild info begin Prebuild version 4.5.0
gyp info spawn C:\Users\Chris\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\Chris\\Sites\\blog\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Chris\\Sites\\blog\\node_modules\\level\\node_modules\\leveldown\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Chris\\Sites\\blog\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Chris\\.node-gyp\\7.3.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Chris\\.node-gyp\\7.3.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Chris\\Sites\\blog\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Chris\\Sites\\blog\\node_modules\\level\\node_modules\\leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Chris\\Sites\\blog\\node_modules\\level\\node_modules\\leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "C:\Users\Chris\Sites\blog\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1225, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (C:\Users\Chris\Sites\blog\node_modules\node-gyp\lib\configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (C:\Users\Chris\Sites\blog\node_modules\node-gyp\lib\configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Now this could be me, as I am doing a clean node install on windows, so I could be missing some other dependencies. It runs fine on my mac

**Comment by bbondy** [comment]
Sorry for the delay, seems to be working now. I'm not sure if some related dep was fixed in the meantime or something else. but I'll close this since it works now.
