### ISSUE TITLE
Unable to install on centos

### ISSUE THREAD

**Issue by danwguy** [Level/leveldown#374]
I recently got a Core VPS host at a2host, which is running CentOS. I am trying to get a node server up and running, I was able to install node and npm from the packages on the website, but whenever I try to run a "sudo npm install" for my server it fails while trying to make leveldown. The output is massive so I will give the first section and the last section, but if any more information is needed, please let me know and I will be more than happy to provide the entire output.

```
> leveldown@1.4.5 install /root/node_server/node_modules/leveldown
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v6.11.1 arch=x64 platform=linux)
make: Entering directory `/root/node_server/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/leveldb_main.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
../../nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/node_server/node_modules/leveldown/6.11.1/include/node/node.h:42,
                 from ../src/batch.cc:1:
```

And the last part...

```
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/root/node_server/node_modules/leveldown/build'
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/root/node_server/node_modules/node-gyp/lib/build.js:258:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/root/node_server/node_modules/node-gyp/lib/build.js:258:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm WARN node_server@0.9.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@1.4.5 (node_modules/leveldown):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@1.4.5 install: `prebuild --install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 2
```

I tried searching around and people are saying install the build-essential packages, which CentOS doesn't have so I tried installing the individual packages that I would need, and they are already installed. Please help, I really need to get this up and running. Thank you.

**Comment by ralphtheninja** [comment]
@danwguy I think you should try to upgrade leveldown to version `1.7.2` if you can. There should be prebuilts made for your platform.

**Comment by ralphtheninja** [comment]
@danwguy How do you pull in leveldown in the first place if it's not part of your package.json?

**Comment by danwguy** [comment]
@ralphtheninja it must be required by one of the dependencies I am using. Here is my package.json, maybe you can see what is forcing the leveldown addon...

```
{
  "name": "test-server",
  "version": "0.0.9",
  "description": "A test for superlogin and couchdb",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Me",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.17.2",
    "cors": "^2.8.3",
    "del": "^3.0.0",
    "express": "^4.15.3",
    "fs": "0.0.1-security",
    "http": "0.0.0",
    "method-override": "^2.3.9",
    "morgan": "^1.8.2",
    "multer": "^1.3.0",
    "nano": "^6.3.0",
    "node-fetch": "^1.7.1",
    "socket.io": "^2.0.3",
    "superlogin": "^0.6.1"
  }
}

```

I have that, then I run "npm install" it does it's thing for a while, then I get the error mentioned in my original post.

**Comment by ralphtheninja** [comment]
@dawnguy `npm ls leveldown` gives me:

```
lms@x240 ~/src/play/leveldowntest
$ npm ls leveldown
test-server@0.0.9 /home/lms/src/play/leveldowntest
└─┬ superlogin@0.6.1
  └─┬ pouchdb@5.3.2
    └── leveldown@1.4.5 
```

So it seems it's `superlogin` that pulls in `pouchdb` which in turn pulls in `leveldown`. Maybe check if superlogin has some updates with an updated version of `pouchdb`.

**Comment by ralphtheninja** [comment]
Linking an issue for reference: https://github.com/pouchdb/pouchdb/issues/6551

**Comment by danwguy** [comment]
Thank you @ralphtheninja  If I forcibly put puchdb in the dependencies before superlogin, will superlogin still try to download pouchdb, or would that be covered already since I added it? Just trying to find the best way to handle this, since superlogin is deciding which version of pouchdb to put in on its own, so I can't change what it calls for. If that makes sense.

**Comment by ralphtheninja** [comment]
@danwguy These things can be tricky indeed. As a workaround you could try something like:

```
npm install
rm node_modules/leveldown -rf
npm i leveldown@1.7.2
```

**Comment by danwguy** [comment]
@ralphtheninja it still fails. Here is what I did...

> npm init

> npm install --save leveldown@1.7.2

So it was a fresh start in a new directory and it still fails to build. Here is the output...

```
prebuild-install info begin Prebuild-install version 2.2.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v48-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/danwguy/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.7.2/leveldown-v1.7.2-node-v48-linux-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.7.2/leveldown-v1.7.2-node-v48-linux-x64.tar.gz
prebuild-install info downloading to @ /home/danwguy/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-linux-x64.tar.gz.29259-fe99ffe2fd8fd.tmp
prebuild-install info renaming to @ /home/danwguy/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-linux-x64.tar.gz
prebuild-install info unpacking @ /home/danwguy/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/danwguy/node_text/node_modules/leveldown/build/Release/leveldown.node
prebuild-install WARN install /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/danwguy/node_text/node_modules/leveldown/build/Release/leveldown.node)
make: Entering directory `/home/danwguy/node_text/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
```
then a whole bunch of those CXX(target) lines, then...

```
In file included from ../src/batch.cc:3:
../../nan/nan.h:45:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/danwguy/.node-gyp/6.11.1/include/node/node.h:42,
                 from ../src/batch.cc:1:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: At global scope:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: At global scope:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:3279: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: At global scope:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:4499: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:4515: error: ‘nullptr’ was not declared in this scope
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/danwguy/.node-gyp/6.11.1/include/node/v8.h:7539: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:192,
                 from ../src/batch.cc:3:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:29: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:37: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:45: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:52: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:71: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:79: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:87: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:96: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:105: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:141: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:149: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:155: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:164: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:171: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:179: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:226: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:234: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:244: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:254: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:266: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:277: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:284: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:290: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:296: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:302: error: expected initializer before ‘<’ token
../src/batch.cc:146: error: expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/home/danwguy/node_text/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab120.19
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/danwguy/node_text/node_modules/leveldown
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN node_text@0.0.9 No repository field.
npm ERR! Linux 2.6.32-042stab120.19
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "leveldown@1.7.2"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/danwguy/node_text/npm-debug.log
```
I am using the following node and npm versions...

>node -v
>v6.11.1

>npm -v
>3.10.10

Any ideas? Please. Sorry to keep bothering, but I gotta get this working.

**Comment by ralphtheninja** [comment]
> Any ideas? Please. Sorry to keep bothering, but I gotta get this working.

There's no bother at all.

Ok. So prebuilts seem to be tricky to get working since `superlogin` et.al. have to be updated so lets not walk that path just now (I can try to push this on a longer perspective). Since you are on centos this _should_ just work by compiling, but compiling fails and this is due to your version of gcc. I think it needs to be at least version 4.8.

What does `g++ --version` return?

**Comment by ralphtheninja** [comment]
I'm no centos expert so you would have to troubleshoot that yourself. A quick search for c++11 and centos gave me https://unix.stackexchange.com/questions/63587/how-to-install-g-4-7-2-c11-on-centos-5-x

**Comment by ralphtheninja** [comment]
@danwguy https://github.com/pouchdb/pouchdb/pull/6639 just got merged, so soon there will be an updated version of `pouchdb`, then we can move on to `superlogin`, which currently are using `pouchdb@5.3.1` so they need to update their dependencies and release a new version, and _then_ you should be able to reinstall prebuilt binaries.

**Comment by ralphtheninja** [comment]
Opened PR [here](https://github.com/colinskow/superlogin/pull/171)
