### ISSUE TITLE
1.7.2 Fails to build on CentOS

### ISSUE THREAD

**Issue by littlebee** [Level/leveldown#375]
see also, https://github.com/mzgoddard/hard-source-webpack-plugin/issues/166, for which I think the solution was to ugrade leveldown used by pouchdb to 1.7.2 (latest package.json)[https://github.com/pouchdb/pouchdb/blob/master/package.json]

I'm trying to install hard-source-webpack-plugin which uses leveldown 1.7.2; https://github.com/Level/leveldown/issues/374:
```
$ npm ls leveldown
zukeeper@6.0.0 /Users/bwilkerson/projects/zulily/htdocs_ems
├─┬ hard-source-webpack-plugin@0.4.9
│ └─┬ level@1.7.0
│   └── leveldown@1.7.2
```

versions:  
```
$ g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
$ node --version
v5.10.0
$ npm --version
3.8.3
```

the error:
```
$ npm install

> leveldown@1.7.2 install /var/www/htdocs/zulily-event-management/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v47-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/bwilkerson/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v47-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/bwilkerson/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v47-linux-x64.tar.gz
prebuild-install info unpack resolved to /var/www/htdocs/zulily-event-management/node_modules/leveldown/build/Release/leveldown.node
prebuild-install WARN install /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/www/htdocs/zulily-event-management/node_modules/leveldown/build/Release/leveldown.node)
make: Entering directory `/var/www/htdocs/zulily-event-management/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
/tmp/ccddLdl7.s: Assembler messages:
/tmp/ccddLdl7.s:359: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o] Error 1
make: Leaving directory `/var/www/htdocs/zulily-event-management/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/node-v5.10.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "/opt/nodejs/node-v5.10.0-linux-x64/bin/node" "/opt/nodejs/node-v5.10.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/htdocs/zulily-event-management/node_modules/leveldown
gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
zukeeper@6.0.0 /var/www/htdocs/zulily-event-management
└── UNMET PEER DEPENDENCY react@0.14.1

npm WARN react-addons-test-utils@0.14.2 requires a peer of react@^0.14.2 but none was installed.
npm WARN hard-source-webpack-plugin@0.4.9 requires a peer of webpack@* but none was installed.
npm WARN zukeeper@6.0.0 license should be a valid SPDX license expression
npm ERR! Linux 2.6.32-279.el6.x86_64
npm ERR! argv "/opt/nodejs/node-v5.10.0-linux-x64/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/htdocs/zulily-event-management/npm-debug.log
npm ERR! code 1

```

**Comment by ralphtheninja** [comment]
Hmm interesting. So first it fails to load the (found cached) binary beause of glibc mismatch, so it falls back to build which also fails.

Maybe related to https://stackoverflow.com/questions/23561136/casablanca-assembly-error-gcc-4-8-1-on-linux-centos#24625093 ?

**Comment by yuanchuan** [comment]
Solved the build problem after trying instructions in:

https://stackoverflow.com/questions/33762854/updating-gcc-on-centos-6-2/33764262#33764262

**Comment by ralphtheninja** [comment]
@littlebee Can you try this and report back?

**Comment by MystK** [comment]
Happens to me too and I'm on CentOS 6.

I followed the GCC part of the link @yuanchuan provided and made sure the env variables were exported on the user that was running the npm i.
