### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Badestrand** [Level/leveldown#408]
Hi

I just cannot get my server to install this package. node-gyp is installed and the latest node js. It can not find the prebuilt library (`leveldown-v2.0.1-node-v59-linux-x64.tar.gz`) and the g++ build step fails (`g++: internal compiler error`).

Does anyone have an idea what I could try to make this work? 

The log:
```
> leveldown@2.0.1 install /var/www/web/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.0.1-leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v2.0.1/leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v2.0.1/leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.2.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/var/www/web/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
deps/leveldb/leveldb.target.mk:148: recipe for target 'Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o' failed
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o] Error 4
make: Leaving directory '/var/www/web/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-98-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/web/node_modules/leveldown
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN react-resize-detector@1.1.0 requires a peer of react@^0.14.7 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-smooth@1.0.0 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-smooth@1.0.0 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.2.1 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.2.1 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recharts@1.0.0-beta.2 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recharts@1.0.0-beta.2 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN web No description
npm WARN web No repository field.
npm WARN web No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@2.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
```

Edit: Versions: gcc 5.4.0, Node v9.2.0, npm 5.5.1

**Comment by ralphtheninja** [comment]
@Badestrand Mind retrying installing leveldown? Should be prebuilt binaries for you. I have no idea of the compiler error.

**Comment by Badestrand** [comment]
@ralphtheninja Perfect, prebuilt library now found, thank you so much!

**Comment by dskrepps** [comment]
@ralphtheninja I'm getting the same error:

```bash
deps/leveldb/leveldb.target.mk:154: recipe for target 'Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o' failed
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o] Error 4
```
There's nothing unusual about this system and everything is up to date:
```bash
dsk@dev:~/checkleveldown$ lsb_release -a                                  
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
dsk@dev:~/checkleveldown$ node -v
v11.2.0
dsk@dev:~/checkleveldown$ npm -v
6.4.1
```

The full verbose output: https://gist.github.com/dskrepps/b2289093e87b3e5bef4bf9836623d806

**Comment by dskrepps** [comment]
Looks like it builds under Node 10. My mistake for not noticing 11 wasn't supported yet. Another part of the project only works on 11 so I'll have to look for another solution.

g++ was: `g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609`
I updated it to: `g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010`
It failed with the same error.

**Comment by ralphtheninja** [comment]
@dskrepps Is there any chance you could get more memory? I.e. shutdown some programs and _only_ compile this code. Or try with a more modern compiler. Although I think `5.4.0` should be enough.
