### ISSUE TITLE
Compile fails on NetBSD

### ISSUE THREAD

**Issue by zilti** [Level/leveldown#418]
Other modules do it, too.

...or provide a binary for NetBSD, of course :P

**Comment by vweevers** [comment]
It should fall back to building from source. Can you please share the output of `npm install leveldown`?

**Comment by zilti** [comment]
Here is the immediate output:
```
lyrion# npm install leveldown

> leveldown@2.1.1 install /node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v2.1.1-node-v57-netbsd-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-netbsd-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v2.1.1/leveldown-v2.1.1-node-v57-netbsd-x64.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v2.1.1/leveldown-v2.1.1-node-v57-netbsd-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.4.0 runtime=node arch=x64 platform=netbsd)
gyp: Undefined variable os_include in /node_modules/leveldown/deps/snappy/snappy.gyp while loading dependencies of /node_modules/leveldown/deps/leveldb/leveldb.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/pkg/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System NetBSD 7.1
gyp ERR! command "node" "/usr/pkg/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/leveldown
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@2.1.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-03T00_19_29_677Z-debug.log
```

The contents of the log file are on termbin: http://termbin.com/zq4u

**Comment by zilti** [comment]
Ok, weird. I've actually set the os_include var in snappy.gyp. Now it fails because it can't find `<endian.h>`; this file is in sys/endian.h.

**Comment by ralphtheninja** [comment]
Need to add a corresponding header file for netbsd, see below:

```
lms@x240 ~/src/level/leveldown (master)
$ find | grep snappy-stubs-public.h
./deps/snappy/freebsd/snappy-stubs-public.h
./deps/snappy/mac/snappy-stubs-public.h
./deps/snappy/snappy-1.1.4/snappy-stubs-public.h.in
./deps/snappy/solaris/snappy-stubs-public.h
./deps/snappy/win32/snappy-stubs-public.h
./deps/snappy/openbsd/snappy-stubs-public.h
./deps/snappy/linux/snappy-stubs-public.h
```

**Comment by ralphtheninja** [comment]
And a `config.h` as well.

**Comment by zilti** [comment]
Alright, it compiled (just before I've seen your replies). `npm install` in the same dir still doesn't work though?

```bash
export CXXPPFLAGS="-DOS_NETBSD"  # What a nasty hack...
export CXXFLAGS="-std=c++11"
cd deps/snappy
ln -s freebsd netbsd
```

and added `, ['OS=="netbsd"',  {'os_include': 'netbsd'}]` to snappy.gyp.

**Comment by ralphtheninja** [comment]
This error seems related to [`sodium-native`](https://github.com/sodium-friends/sodium-native), but that's a `devDependency` so should be fine for production. You might want to create an issue there as well.

**Comment by ralphtheninja** [comment]
@zilti Could you try `npm install --production` just so we can rule that out?

**Comment by zilti** [comment]
Can confirm, this works. (As was to be expected after it compiled fine with gyp).
