### ISSUE TITLE
Fails to install when installing leveldown or any dependant project as root

### ISSUE THREAD

**Issue by interfect** [Level/leveldown#516]
The `scuttlebot` NPM module depends on `leveldown@3.0.2`.

Scuttlebot fails to install globally for all users (on my mac), and blames Leveldown:

```
Vyoma:~ anovak$ sudo npm install -g scuttlebot
npm WARN notice [SECURITY] bl has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=bl&version=0.8.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
/opt/local/bin/scuttlebot -> /opt/local/lib/node_modules/scuttlebot/bin.js
/opt/local/bin/sbot -> /opt/local/lib/node_modules/scuttlebot/bin.js

> fsevents@1.2.4 install /opt/local/lib/node_modules/scuttlebot/node_modules/fsevents
> node install

node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.4 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /opt/local/lib/node_modules/scuttlebot/node_modules/fsevents
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/local/lib/node_modules/scuttlebot/node_modules/fsevents
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> sodium-native@2.2.2 install /opt/local/lib/node_modules/scuttlebot/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> leveldown@3.0.2 install /opt/local/lib/node_modules/scuttlebot/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/Users/anovak/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/local/lib/node_modules/scuttlebot/node_modules/leveldown/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/local/lib/node_modules/scuttlebot/node_modules/leveldown
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/scuttlebot/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anovak/.npm/_logs/2018-10-20T23_25_47_432Z-debug.log
```

Leveldown itself refuses to install:

```
Vyoma:~ anovak$ sudo npm install -g leveldown@3.0.2

> leveldown@3.0.2 install /opt/local/lib/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/Users/anovak/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/local/lib/node_modules/leveldown/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/local/lib/node_modules/leveldown
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anovak/.npm/_logs/2018-10-20T23_29_59_238Z-debug.log
```

If I add `--unsafe-perm=true --allow-root` onto the command line, the install of `scuttlebot` or `leveldown` succeeds.

Please modify the Leveldown build process so that it can build as a dependency of system-level-installed software without extra scary-looking unsafety options.

sudo npm install -g leveldown@3.0.2 --unsafe-perm=true --allow-root

**Comment by ralphtheninja** [comment]
Please fix your permissions. This has nothing to do with leveldown. Before jumping to conclusions, maybe you should read your log more carefully.

```
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.4 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64' 
```

Or have you told developers of `fsevents` to modify their build process as well?

**Comment by dominictarr** [comment]
@interfect this isn't a leveldown problem, this is intended npm behaviour. if you run npm with root, it runs all scripts as `nobody`. really, you shouldn't run npm as root... I'd recommend installing node via `nvm` and it will set it up inside your local user and not have this problem.

**Comment by dominictarr** [comment]
@interfect this isn't a leveldown problem, this is intended npm behaviour. if you run npm with root, it runs all scripts as `nobody`. really, you shouldn't run npm as root... I'd recommend installing node via `nvm` and it will set it up inside your local user and not have this problem.

**Comment by dominictarr** [comment]
how does prebuildify do it? it just checks all the versions in and doesn't use a build script at all?

**Comment by ralphtheninja** [comment]
> how does prebuildify do it? it just checks all the versions in and doesn't use a build script at all?

The module itself contains _all_ prebuilt binaries, so it's part of the tarball from npm, so no extra scripts are running as `nobody` to e.g. download files etc. I _think_ this is why.

**Comment by interfect** [comment]
I just tried `sudo su -`ing and installing from there; that didn't work either.

It looks like you can tell npm that `-g` means to install to a user directory, or you can make your user own the system install directory, but I really want to be able to install things for all users and have them owned by root, as well-behaved system software should be.

October 21, 2018 4:31 PM, "Lars-Magnus Skog" <notifications@github.com (mailto:notifications@github.com?to=%22Lars-Magnus%20Skog%22%20<notifications@github.com>)> wrote:
	Another observation I just made is that sodium-native works well, which has a different system with bundled binaries. Maybe converting leveldown to prebuildify will solve this problem. 

	In the meantime, is there some way you could change your system so you don't need to use sudo when installing globally? This could be a workaround.

**Comment by vweevers** [comment]
> but I really want to be able to install things for all users and have them owned by root, as well-behaved system software should be.

Anyone can publish packages to npm, that's different from curated system software.

To follow progress on `prebuildify`, see #482. There's nothing else we can do, so I'm closing this.
