### ISSUE TITLE
Installation fails on FreeBSD 11

### ISSUE THREAD

**Issue by interkosmos** [Level/leveldown#523]
Installation of `leveldown` fails on FreeBSD 11:

```
$ npm install leveldown
prebuild-install WARN install No prebuilt binaries found (target=8.12.0 runtime=node arch=x64 platform=freebsd)
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/bin/python3.6 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System FreeBSD 11.2-RELEASE-p4
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/user/project/node_modules/leveldown
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@2.1.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-10-25T18_55_57_124Z-debug.log
```

**Comment by ralphtheninja** [comment]
@interkosmos I'm guessing you have problems with any native addons and I _think_ this is related to python 3.6, see https://github.com/nodejs/node-gyp#on-unix

**Comment by interkosmos** [comment]
I could revolve the issue with:
```
$ npm config set python /usr/local/bin/python2.7
$ npm i -f
```
