### ISSUE TITLE
Leveldown causes projects using worker_threads to fail

### ISSUE THREAD

**Issue by jobe451** [Level/leveldown#599]
Node 10.5 introduced worker threads.
https://nodejs.org/api/worker_threads.html

If a script using worker-threads references leveldown, it will fail. Indpendent whether leveldown is used at all, used only in the main-thread or used by workers.

the following node script needs to be called with the "--experimental-worker" flag.

```javascript
const { Worker, isMainThread } = require('worker_threads');
//const leveldown = require('leveldown');

if (isMainThread) {
	new Worker(__filename, {workerData: {}});
	console.log("main thread executed");
} else {
	console.log("worker is working")
	setInterval(
		() => {
			console.log("1 second did pass");
		} , 1000);
}
```

When it is run, with the 2nd line (leveldown) uncommented, it will fail with 
```
main thread executed

events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (C:\Users\d.keller\workspace js\mmFileFiltersTs\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\d.keller\workspace js\mmFileFiltersTs\node_modules\leveldown\leveldown.js:3:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Emitted 'error' event at:
    at Worker.[kOnErrorMessage] (internal/worker.js:332:10)
    at Worker.[kOnMessage] (internal/worker.js:342:37)
    at MessagePort.Worker.(anonymous function).on (internal/worker.js:279:57)
    at MessagePort.emit (events.js:189:13)
    at MessagePort.onmessage (internal/worker.js:84:8)
```

Tested with node version 10.15.1

**Comment by vweevers** [comment]
See https://github.com/Level/level/issues/117#issuecomment-414632676. TLDR: native addons are not supported yet by Node, and in the case of `leveldown` it is ill-advised anyway.
