### ISSUE TITLE
npm install fails on leveldown@3.0.0

### ISSUE THREAD

**Issue by bricksphd** [Level/leveldown#698]
I recently reformatted my Windows 10 box. My nodejs project that compiled fine with "npm install" now fails with this error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

As I've looked at other issues that seem relevant to this problem, I've gathered what I think is l relevant information to this problem. Forgive me if I'm way off or if the solution is super obvious.

Relevant lines from debug.log:

```
1065 info lifecycle leveldown@3.0.0~install: leveldown@3.0.0
1066 verbose lifecycle leveldown@3.0.0~install: unsafe-perm in lifecycle true
1067 verbose lifecycle leveldown@3.0.0~install: PATH: C:\Users\<user_name>\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\<project_path>\node_modules\pouchdb\node_modules\leveldown\node_modules\.bin;C:\<project_path>\node_modules\pouchdb\node_modules\.bin;C:\<project_path>\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\<user_name>bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\PuTTY;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;C:\Users\<user_name>AppData\Local\Microsoft\WindowsApps;C:\Users\<user_name>AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<user_name>AppData\Local\Yarn\bin;C:\Users\<user_name>AppData\Roaming\npm;C:\Users\<user_name>AppData\Local\Box\Box Edit;C:\Program Files\Java\jdk-13.0.1\bin;C:\Users\<user_name>AppData\Roaming\npm
1068 verbose lifecycle leveldown@3.0.0~install: CWD: C:\<project_path>>\node_modules\pouchdb\node_modules\leveldown
1069 silly lifecycle leveldown@3.0.0~install: Args: [ '/d /s /c', 'prebuild-install || node-gyp rebuild' ]
1070 silly lifecycle leveldown@3.0.0~install: Returned: code: 1  signal: null
1071 info lifecycle leveldown@3.0.0~install: Failed to exec install script
```
...
```
1082 verbose stack Error: leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
1082 verbose stack Exit status 1
1082 verbose stack     at EventEmitter.<anonymous> (C:\Users\<user_name>AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
1082 verbose stack     at EventEmitter.emit (events.js:223:5)
1082 verbose stack     at ChildProcess.<anonymous> (C:\Users\<user_name>AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1082 verbose stack     at ChildProcess.emit (events.js:223:5)
1082 verbose stack     at maybeClose (internal/child_process.js:1021:16)
1082 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
1083 verbose pkgid leveldown@3.0.0
1084 verbose cwd C:\<project_path>
1085 verbose Windows_NT 10.0.17763
1086 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user_name>\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "cookie-parser"
1087 verbose node v12.14.1
1088 verbose npm  v6.13.6
1089 error code ELIFECYCLE
1090 error errno 1
1091 error leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
1091 error Exit status 1
1092 error Failed at the leveldown@3.0.0 install script.
1092 error This is probably not a problem with npm. There is likely additional logging output above.
1093 verbose exit [ 1, true ]
```

Relevant software installed:

- node -v -> 12.14.1
- npm -v -> 6.13.6
- node-gyp -v -> 6.1.0
- msbuildtools 2017 & 2019

**Comment by vweevers** [comment]
For node >= 12, `leveldown@5` is the minimum version.

**Comment by bricksphd** [comment]
Thank you.
